{% set name = "tdscha" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tdscha-{{ version }}.tar.gz
  sha256: ee30735bbf828fb9e7f7bca48b48be81271bc30cb095296de1876e3d22863b9d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - mpi4py
    - pypar
    - numpy
    - pip
  run:
    - python
    - ase
    - scipy
    - cellconstructor
    - python-sscha
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - tdscha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SSCHAcode/tdscha
  summary: Time Dependent Self Consistent Harmonic Approximation
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
