schema_version: 1

context:
  name: tdscha
  version: "1.6.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tdscha-${{ version }}.tar.gz
  sha256: 58ba0b4dd1d87a0c0b6eaf397296f1448f586766b6b6ad6975dae5ab6d9b3d4d

build:
  number: 1
  skip: not linux
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: osx
      then: llvm-openmp
    - if: linux
      then: libgomp
    - cmake
    - pkg-config
  host:
    - python
    - mpi4py
    - pypar
    - numpy
    - pip
    - meson-python
    - libblas
    - liblapack
  run:
    - python
    - ase
    - scipy
    - cellconstructor
    - python-sscha
    - ${{ pin_compatible('numpy') }}

tests:
  - python:
      imports:
        - tdscha
      pip_check: true

about:
  summary: Time Dependent Self Consistent Harmonic Approximation
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://github.com/SSCHAcode/tdscha

extra:
  recipe-maintainers:
    - jan-janssen
